AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rank-six-api

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        MONGODB_URI: "<INSERT_MONGODB_URI_HERE>"
        UPSTASH_REDIS_REST_URL: "<INSERT_UPSTASH_REDIS_REST_URL_HERE>"
        UPSTASH_REDIS_REST_TOKEN: "<INSERT_UPSTASH_REDIS_REST_TOKEN_HERE>"

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createUser/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 15
      MemorySize: 2048
      Architectures:
        - x86_64
      Events:
        CreateUser:
          Type: HttpApi
          Properties:
            Path: /user
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createSession/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 10
      Architectures:
        - x86_64
      Events:
        FetchPlayers:
          Type: HttpApi
          Properties:
            Path: /sessions
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

  EvaluateGuessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: evaluateGuess/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 10
      MemorySize: 2048
      Architectures:
        - x86_64
      Events:
        EvaluateGuess:
          Type: HttpApi
          Properties:
            Path: /guess
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts