AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  rank-six-api

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 2048
    Timeout: 10
    Architectures:
      - arm64
    Environment:
      Variables:
        MONGODB_URI: ''
        UPSTASH_REDIS_REST_URL: ''
        UPSTASH_REDIS_REST_TOKEN: ''
        MONGODB_DATABASE: ''
        MONGODB_PLAYER_COLLECTION: ''
        MONGODB_USER_COLLECTION: ''
        MONGODB_SESSIONS_COLLECTION: ''

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createUser/
      Handler: index.handler
      Events:
        CreateUser:
          Type: HttpApi
          Properties:
            Path: /create-user
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - index.ts

  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createSession/
      Handler: index.handler
      Events:
        CreateSession:
          Type: HttpApi
          Properties:
            Path: /create-session
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - index.ts

  EvaluateGuessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: evaluateGuess/
      Handler: index.handler
      Events:
        EvaluateGuess:
          Type: HttpApi
          Properties:
            Path: /evaluate-guess
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - index.ts

  FetchSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetchSession/
      Handler: index.handler
      Events:
        FetchSession:
          Type: HttpApi
          Properties:
            Path: /fetch-session
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - index.ts

  FetchUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetchUser/
      Handler: index.handler
      Events:
        FetchUser:
          Type: HttpApi
          Properties:
            Path: /fetch-user
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - index.ts